# Generated by Django 3.2.7 on 2021-09-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
    ]
