# Generated by Django 2.1.11 on 2021-11-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0004_auto_20210917_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('email', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactivate')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='country_info', to='App_Dashboard.Country')),
            ],
        ),
    ]
