# Generated by Django 2.1.11 on 2021-11-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0005_designerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerinfo',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='country_info', to='App_Dashboard.Country'),
        ),
    ]
