# Generated by Django 2.1.11 on 2021-11-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0006_auto_20211125_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerinfo',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='country_info', to='App_Dashboard.Country'),
        ),
    ]
