# Generated by Django 2.1.11 on 2022-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0010_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='post',
            field=models.IntegerField(max_length=255),
        ),
    ]
