# Generated by Django 2.1.11 on 2022-01-03 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Dashboard', '0013_reply_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
                ('designer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
