# Generated by Django 2.1.11 on 2022-01-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0014_designermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designermessage',
            name='designer_user',
            field=models.IntegerField(),
        ),
    ]
