# Generated by Django 2.1.11 on 2022-01-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0016_auto_20220104_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='designermessage',
            name='reply_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
