# Generated by Django 2.1.11 on 2021-12-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_auto_20211203_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Designer')]),
        ),
    ]
