# Generated by Django 2.1.11 on 2021-12-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0009_auto_20211206_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
