# Generated by Django 2.1.11 on 2021-12-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0013_auto_20211206_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
