# Generated by Django 2.1.11 on 2021-12-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0016_auto_20211207_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
